export const FETCH_SLIDER_REQUEST = 'FETCH_SLIDER_REQUEST';
export const FETCH_SLIDER_SUCCESS = 'FETCH_SLIDER_SUCCESS';
export const FETCH_SLIDER_ERROR = 'FETCH_SLIDER_ERROR';
export const FETCH_WEBSITE_REQUEST = 'FETCH_WEBSITE_REQUEST';
export const FETCH_WEBSITE_SUCCESS = 'FETCH_WEBSITE_SUCCESS';
export const FETCH_WEBSITE_ERROR = 'FETCH_WEBSITE_ERROR';